[[gbif-whats-in-a-name]]
== GBIF: What's in a name? 

=== GBIF: The Global Biodiversity Information Facility

GBIF is the organization’s name in both formal and informal usage.

Any stand-alone electronic or print document should include the full name somewhere in the text. This can take the form of a standard header and/or boilerplate description, but we further recommend its inclusion in the body of the text to accommodate the fact that many aggregators will simply lift the text directly from other websites and services (e.g. Eurekalert, scidev.net). We cannot afford the arrogance of assuming that people will know what "GBIF" stands for.

This recommendation is relaxed on GBIF.org itself, where it is safer to assume that readers will receive other cues.

=== GBIF Secretariat

=== GBIF Participants

- What is referred to as an "Other Associate Participant" in the MOU can in practice be called an "Organizational Participant" or OAP (which then also works as an acronym for "Organizational Associate Participant")

=== GBIF network
